python train.py \
--data /home/lxx/WinDisk/dataset/lrs2  \
--data_name 'LRS2' \
--checkpoint_dir './output/checkpoint' \
--visual_front_checkpoint '/home/lxx/PycharmProjects/Lip-to-Speech-Synthesis-in-the-Wild/data/checkpoints/LRS2_front_PT.ckpt' \
--asr_checkpoint '/home/lxx/PycharmProjects/Lip-to-Speech-Synthesis-in-the-Wild/data/checkpoints/LRS2_ASR.ckpt' \
--batch_size 4 \
--epochs 200 \
--eval_step 3000 \
--dataparallel \
--gpu 0
